Feature/vvahwr 250
DEFRA/ffc-ahwr-frontend pull request #74
Opened 2022-05-24 18:40 UTC by govTechSatish

2022-05-26 17:01 UTC, st3v3nhunt requested changes

2022-05-27 08:34 UTC, govTechSatish commented on app/routes/farmer-apply/org-review.js
> +function getYesNoRadios (previousAnswer, errorText) {
Good Point. I thought but miss this.

2022-05-27 10:53 UTC, shivanshuit914 commented on app/constants/species-content.js
> +    errorText: 'Select yes if there were 51 or more pigs at the time of the review',
Thanks, Steve, My changes are for vet and in diff file app/constants/species-content-vet.js :)

2022-05-30 09:58 UTC, shivanshuit914 approved these changes

2022-05-30 10:26 UTC, merged